# Generated by Django 5.0.7 on 2024-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.IntegerField(null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.menu')),
            ],
        ),
    ]
